# Project Info
site_name: MonitorKit
site_description: >-
  Monitoring-as-Code is an approach which enables the creation and management of your own set of dashboards and monitors so that you can understand what's happening in your application.

# Repository
repo_url: https://github.mheducation.com/monitoring-as-code/monitorkit/
repo_name: monitorkit
edit_uri: edit/main/markdown/
docs_dir: markdown/

# Configuration
theme:
  name: material
  # custom_dir: overrides
  include_search_page: true
  search_index_only: true
  language: en
  favicon: img/favicon.ico
  icon:
    logo: octicons/graph-24
    repo: fontawesome/brands/github
  font: false
  palette:
    scheme: preference
    accent: indigo
  features:
    - instant
    - search.highlight
    - header.hide

# Custom CSS
extra_css:
  - static/styles.css

# Custom JS
# extra_javascript:
#   - static/scripts.js

module_name: markdown-macros

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      # linenums: true
      # linenums_style: pymdownx.inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      toc_depth: 5
      permalink: true
      # slugify: pymdownx.slugs.uslugify
  - pymdownx.tabbed
  - pymdownx.tilde

# Plugins
plugins:
  - git-revision-date
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true
  - macros
  - search:
      prebuild_index: true
      lang:
        - en

# Social Icons
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.mheducation.com/monitoring-as-code/monitorkit/
    - icon: fontawesome/brands/slack
      link: https://mheducation.slack.com/archives/CGQ05TMFE

# Navigation
nav:
  - index.md
  - Features:
      - features-terraform.md
