# Project Info
site_name: International Travel Planning Guide
site_url: https://travel.readme.guide
site_author: Ryan Parman
site_description: >-
  International Travel Planning Guide is a short book will collected tips, tricks, patterns, and habits for those who travel from USA/Canada to other countries.

# Repository
repo_url: https://github.com/skyzyx/international-travel-planning-guide/
repo_name: skyzyx/international-travel-planning-guide
edit_uri: edit/main/markdown/
docs_dir: markdown/
copyright: Copyright &copy; 2023 Ryan Parman
use_directory_urls: true

# Configuration
theme:
  name: material
  custom_dir: overrides
  include_search_page: true
  search_index_only: true
  language: en
  favicon: favicon.ico
  font: false

  icon:
    logo: octicons/graph-24
    repo: fontawesome/brands/github
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css: fontawesome/brands/css3

  palette:
    scheme: preference
    accent: indigo

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    - header.hide
    - instant
    # - navigation.expand
    # - navigation.footer
    # - navigation.indexes
    - navigation.instant
    - navigation.path
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

# Custom CSS
extra_css:
  - static/styles.css

# Custom JS
# extra_javascript:
#   - static/scripts.js

module_name:
  markdown-macros:

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      linenums: false
      linenums_style: table
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: skyzyx
      repo: international-travel-planning-guide
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - abbreviations.md
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      toc_depth: 5
      permalink: true

# Plugins
plugins:
  - git-committers:
      repository: skyzyx/international-travel-planning-guide
      branch: main
  - git-revision-date
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
  - macros
  - meta:
      meta_file: "**/.meta.yml"
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
      # js_files:
      #   - my/javascript/dir/file1.js
      #   - my/javascript/dir/file2.js
      css_files:
        - static/styles.css
  # - offline:
  #     enabled: true
  # - optimize:
  #     enabled: true
  - privacy:
      enabled: true
      links: true
      links_noopener: true
      links_attr_map:
        target: _blank
  - redirects:
      redirect_maps:
        # "old.md": "new.md"
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      prebuild_index: true
      lang:
        - en
  - social:
      cards: true
      cards_font: Roboto
      cards_color:
        fill: "#171e21"
        text: "#ffffff"
  - tags:
      enabled: true
      tags_slugify_separator: "-"
      tags_compare: !!python/name:material.plugins.tags.plugin.casefold
      tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - typeset

extra:
  # alternate:
  #   - name: English
  #     link: /en/
  #     lang: en
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by using our <a href="https://github.com/skyzyx/international-travel-planning-guide/issues/new/?title=[Feedback]+{title}&body={url}" target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: "Cookie consent: Please help make our docs better!"
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Google Analytics
    actions:
      - accept
      - reject
      - manage
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/skyzyx/international-travel-planning-guide/
      name: "GitHub: @skyzyx"
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@FlailingWildly
      name: "YouTube: @FlailingWildly"
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/skyzyx/
      name: "Docker: @skyzyx"
    - icon: fontawesome/brands/mastodon
      link: https://techhub.social/@skyzyx
      name: "Mastodon: @skyzyx"
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/skyzyx
      name: "Twitter: @skyzyx"
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/rparman
      name: "LinkedIn: rparman"
  tags:
    HTML5: html
    JavaScript: js
    CSS: css

# Navigation
nav:
  - Guide:
      - Welcome: index.md
      - "Travel Documents":
          - guide/passport.md
          - guide/trusted-traveler.md
      - "Prepare for your Trip":
          - guide/technology-tips.md
          - guide/apps-to-install.md
          - guide/travel-products.md
          - guide/electrical.md
          - guide/timezones.md
          - guide/currency.md
          - guide/register-travel.md
      - "Safety Advice for Marginalized Groups":
          - guide/lgbtqia-travelers.md
          - guide/women-travelers.md
          - guide/elderly-travelers.md
          - guide/student-youth-travelers.md
      - "Traveling Abroad":
          - guide/dear-american-travelers.md
          - guide/customs-abroad.md
          - guide/cybersecurity.md
          - guide/travel-sim.md
          - guide/driving.md
          - guide/covid-19.md
          - guide/vaccination.md
          - guide/embassies.md
      - "Coming Home":
          - guide/customs-home.md
  # - Template:
  #     - template.md
  - Support this Guide:
      - support-us/index.md
      - support-us/charity.md
      - Share this guide: support-us/share-guide.md
      - Like and share video: support-us/watch-youtube.md
      - Buy us a gift: support-us/wishlist.md
      - Become our patron: support-us/become-patron.md
      - support-us/github-sponsorship.md
      - support-us/buy-book.md
      - support-us/sponsor-guide.md
      - support-us/sponsor-video.md
  - Meta:
      - meta/ethics.md
      - meta/privacy.md
      - meta/colophon.md
